#cloud-config
# vim: syntax=yaml


ntp:
  enabled: true

package_update: false
package_upgrade: false
package_reboot_if_required: false

preserve_hostname: false
manage_etc_hosts: true
hostname: ${hostname}

ssh_pwauth: false

growpart:
  mode: auto
  devices: ['/']

ssh_deletekeys: true
ssh_keys:
  ed25519_public: "${host_ed25519_pub_key}"
  ed25519_private: |
    ${host_ed25519_priv_key}

disable_root: true

timezone: "America/New_York"

# Restart the network so that the correct dhcp client name is given to the
#   server.
runcmd:
  - [dhclient, -r, ens3]
  - [netplan, apply]
